set(TARGET llama-self-layer-prefill-quality)
add_executable(${TARGET} main.cpp)
target_link_libraries(${TARGET} PRIVATE llama ${CMAKE_THREAD_LIBS_INIT})
target_compile_features(${TARGET} PRIVATE cxx_std_17)
install(TARGETS ${TARGET} RUNTIME)

set(TARGET2 llama-attention-correlation)
add_executable(${TARGET2} attention_correlation.cpp)
target_link_libraries(${TARGET2} PRIVATE llama ${CMAKE_THREAD_LIBS_INIT})
target_compile_features(${TARGET2} PRIVATE cxx_std_17)
install(TARGETS ${TARGET2} RUNTIME)

set(TARGET3 llama-debug-correlation)
add_executable(${TARGET3} debug_correlation.cpp)
target_link_libraries(${TARGET3} PRIVATE llama ${CMAKE_THREAD_LIBS_INIT})
target_compile_features(${TARGET3} PRIVATE cxx_std_17)
install(TARGETS ${TARGET3} RUNTIME)

set(TARGET4 llama-selection-overlap)
add_executable(${TARGET4} selection_overlap.cpp)
target_link_libraries(${TARGET4} PRIVATE llama ${CMAKE_THREAD_LIBS_INIT})
target_compile_features(${TARGET4} PRIVATE cxx_std_17)
install(TARGETS ${TARGET4} RUNTIME)

set(TARGET5 llama-token-overlap)
add_executable(${TARGET5} token_overlap.cpp)
target_link_libraries(${TARGET5} PRIVATE llama ${CMAKE_THREAD_LIBS_INIT})
target_compile_features(${TARGET5} PRIVATE cxx_std_17)
install(TARGETS ${TARGET5} RUNTIME)
